# Generated by Django 2.2.3 on 2019-07-25 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=2, verbose_name='性别')),
                ('staff_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='工号')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='岗位名称')),
                ('score', models.IntegerField(verbose_name='基础分数')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('score', models.FloatField(max_length=10, verbose_name='评分')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('remark', models.TextField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='Performance.Employee', to_field='name', verbose_name='员工姓名')),
                ('position_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='position', to='Performance.Position', to_field='name', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
    ]
